### ISSUE TITLE
Is there an input size limit?

### ISSUE THREAD

**Issue by nemobis** [osma/annif#11]
I just entered 200 kB of text in http://api.annif.org/doc/#!/Automatic32subject32indexing/post_autoindex and I've got a sensible response in a short time but I'm not sure whether this is frowned upon. Is the text being truncated after some point?

**Comment by osma** [comment]
There is none. The input will be processed in chunks. The longer input you submit, the longer it will take to process.

Please note that this (and api.annif.org) is the repo of a discontinued prototype. The successor is being developed at https://github.com/NatLibFi/Annif and it is available for testing at http://dev.annif.org

**Comment by osma** [comment]
I mean, there is no limit. In practice you might hit one but it will take much more than 200kB to get there.

**Comment by nemobis** [comment]
Osma Suominen, 01/10/2018 22:31:
> I mean, there is no limit. In practice you might hit one but it will 
> take much more than 200kB to get there.

Thanks! And sorry for not seeing the other repo at first.

**Comment by osma** [comment]
@nemobis I've now added a notice in the README marking this repo as obsolete (should have done that a long time ago!). Also, the redesigned [annif.org](http://annif.org) website now represents the new implementation. Thanks for the reminder :)

**Comment by nemobis** [comment]
Osma Suominen, 22/10/2018 17:03:
> @nemobis <https://github.com/nemobis> I've now added a notice in the 
> README marking this repo as obsolete (should have done that a long time 
> ago!). Also, the redesigned annif.org <http://annif.org> website now 
> represents the new implementation. Thanks for the reminder :)

Thank you!
